-- MySQL Script generated by MySQL Workbench
-- Sun Nov 21 18:34:42 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema covid
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema covid
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `covid` DEFAULT CHARACTER SET utf8 ;
USE `covid` ;

-- -----------------------------------------------------
-- Table `covid`.`PERSONA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `covid`.`PERSONA` (
  `CUIL` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Apellido` VARCHAR(45) NOT NULL,
  `Sexo` VARCHAR(45) NOT NULL,
  `Telefono` VARCHAR(12) NULL,
  `Fecha_nacimiento` DATE NOT NULL,
  PRIMARY KEY (`CUIL`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `covid`.`HOSPITAL`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `covid`.`HOSPITAL` (
  `IdHospital` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Ciudad` VARCHAR(45) NOT NULL,
  `Direccion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`IdHospital`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `covid`.`PLANTA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `covid`.`PLANTA` (
  `IdPlanta` INT NOT NULL,
  `Especialidad` VARCHAR(45) NOT NULL,
  `IdHospital` INT NOT NULL,
  PRIMARY KEY (`IdPlanta`, `IdHospital`),
  INDEX `fk_PLANTA_HOSPITAL1_idx` (`IdHospital` ASC) VISIBLE,
  CONSTRAINT `fk_PLANTA_HOSPITAL1`
    FOREIGN KEY (`IdHospital`)
    REFERENCES `covid`.`HOSPITAL` (`IdHospital`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `covid`.`HABITACION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `covid`.`HABITACION` (
  `IdHabitacion` INT NOT NULL,
  `Observaciones` VARCHAR(45) NOT NULL,
  `Nro_Camas` INT NOT NULL,
  `IdPlanta` INT NOT NULL,
  PRIMARY KEY (`IdHabitacion`, `IdPlanta`),
  INDEX `fk_HABITACION_PLANTA1_idx` (`IdPlanta` ASC) VISIBLE,
  CONSTRAINT `fk_HABITACION_PLANTA1`
    FOREIGN KEY (`IdPlanta`)
    REFERENCES `covid`.`PLANTA` (`IdPlanta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `covid`.`PACIENTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `covid`.`PACIENTE` (
  `CUIL` INT NOT NULL,
  `Ocupación` VARCHAR(45) NOT NULL,
  `Estuvo_de_Viaje` VARCHAR(45) NOT NULL,
  `Acatamiento_DNU` VARCHAR(45) NOT NULL,
  `IdHospital` INT NOT NULL,
  `IdHabitacion` INT NULL,
  `InicioInternacion` DATE NULL,
  `FinInternacion` DATE NULL,
  PRIMARY KEY (`CUIL`, `IdHospital`),
  INDEX `fk_PACIENTE_HOSPITAL1_idx` (`IdHospital` ASC) VISIBLE,
  INDEX `fk_PACIENTE_HABITACION1_idx` (`IdHabitacion` ASC) VISIBLE,
  CONSTRAINT `fk_PACIENTE_PERSONA`
    FOREIGN KEY (`CUIL`)
    REFERENCES `covid`.`PERSONA` (`CUIL`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PACIENTE_HOSPITAL1`
    FOREIGN KEY (`IdHospital`)
    REFERENCES `covid`.`HOSPITAL` (`IdHospital`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PACIENTE_HABITACION1`
    FOREIGN KEY (`IdHabitacion`)
    REFERENCES `covid`.`HABITACION` (`IdHabitacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `covid`.`PROFESIONAL`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `covid`.`PROFESIONAL` (
  `CUIL` INT NOT NULL,
  PRIMARY KEY (`CUIL`),
  CONSTRAINT `fk_PROFESIONAL_PERSONA1`
    FOREIGN KEY (`CUIL`)
    REFERENCES `covid`.`PERSONA` (`CUIL`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `covid`.`MEDICO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `covid`.`MEDICO` (
  `CUIL` INT NOT NULL,
  `Especialidad` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`CUIL`),
  CONSTRAINT `fk_MEDICO_PROFESIONAL1`
    FOREIGN KEY (`CUIL`)
    REFERENCES `covid`.`PROFESIONAL` (`CUIL`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `covid`.`ENFERMERA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `covid`.`ENFERMERA` (
  `CUIL` INT NOT NULL,
  `Turno_Inicio` VARCHAR(45) NULL,
  `Turno_Fin` VARCHAR(45) NULL,
  `IdPlanta` INT NOT NULL,
  PRIMARY KEY (`CUIL`),
  INDEX `fk_ENFERMERA_PLANTA1_idx` (`IdPlanta` ASC) VISIBLE,
  CONSTRAINT `fk_ENFERMERA_PROFESIONAL1`
    FOREIGN KEY (`CUIL`)
    REFERENCES `covid`.`PROFESIONAL` (`CUIL`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ENFERMERA_PLANTA1`
    FOREIGN KEY (`IdPlanta`)
    REFERENCES `covid`.`PLANTA` (`IdPlanta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `covid`.`CALENDARIO_VACUNACION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `covid`.`CALENDARIO_VACUNACION` (
  `CUIL` INT NOT NULL,
  `Fecha` DATE NULL,
  `Marca` VARCHAR(45) NULL,
  `Lugar` VARCHAR(45) NULL,
  `Lote` VARCHAR(45) NULL,
  PRIMARY KEY (`CUIL`),
  INDEX `fk_CALENDARIO_VACUNACION_PACIENTE1_idx` (`CUIL` ASC) VISIBLE,
  CONSTRAINT `fk_CALENDARIO_VACUNACION_PACIENTE1`
    FOREIGN KEY (`CUIL`)
    REFERENCES `covid`.`PACIENTE` (`CUIL`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `covid`.`RESPONSABLE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `covid`.`RESPONSABLE` (
  `RESPONSABLE_CUIL` INT NOT NULL,
  `PACIENTE_CUIL` INT NOT NULL,
  PRIMARY KEY (`RESPONSABLE_CUIL`, `PACIENTE_CUIL`),
  INDEX `fk_RESPONSABLE_PACIENTE1_idx` (`PACIENTE_CUIL` ASC) VISIBLE,
  CONSTRAINT `fk_RESPONSABLE_PERSONA1`
    FOREIGN KEY (`RESPONSABLE_CUIL`)
    REFERENCES `covid`.`PERSONA` (`CUIL`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_RESPONSABLE_PACIENTE1`
    FOREIGN KEY (`PACIENTE_CUIL`)
    REFERENCES `covid`.`PACIENTE` (`CUIL`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `covid`.`INYECTA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `covid`.`INYECTA` (
  `PROFESIONAL_CUIL` INT NOT NULL,
  `PACIENTE_CUIL` INT NOT NULL,
  PRIMARY KEY (`PROFESIONAL_CUIL`, `PACIENTE_CUIL`),
  INDEX `fk_PROFESIONAL_has_CALENDARIO_VACUNACION_CALENDARIO_VACUNAC_idx` (`PACIENTE_CUIL` ASC) VISIBLE,
  INDEX `fk_PROFESIONAL_has_CALENDARIO_VACUNACION_PROFESIONAL1_idx` (`PROFESIONAL_CUIL` ASC) VISIBLE,
  CONSTRAINT `fk_PROFESIONAL_has_CALENDARIO_VACUNACION_PROFESIONAL1`
    FOREIGN KEY (`PROFESIONAL_CUIL`)
    REFERENCES `covid`.`PROFESIONAL` (`CUIL`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PROFESIONAL_has_CALENDARIO_VACUNACION_CALENDARIO_VACUNACION1`
    FOREIGN KEY (`PACIENTE_CUIL`)
    REFERENCES `covid`.`CALENDARIO_VACUNACION` (`CUIL`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `covid`.`TRABAJA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `covid`.`TRABAJA` (
  `IdHospital` INT NOT NULL,
  `CUIL` INT NOT NULL,
  PRIMARY KEY (`IdHospital`, `CUIL`),
  INDEX `fk_HOSPITAL_has_PROFESIONAL_PROFESIONAL1_idx` (`CUIL` ASC) VISIBLE,
  INDEX `fk_HOSPITAL_has_PROFESIONAL_HOSPITAL1_idx` (`IdHospital` ASC) VISIBLE,
  CONSTRAINT `fk_HOSPITAL_has_PROFESIONAL_HOSPITAL1`
    FOREIGN KEY (`IdHospital`)
    REFERENCES `covid`.`HOSPITAL` (`IdHospital`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_HOSPITAL_has_PROFESIONAL_PROFESIONAL1`
    FOREIGN KEY (`CUIL`)
    REFERENCES `covid`.`PROFESIONAL` (`CUIL`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `covid`.`FALLECIDO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `covid`.`FALLECIDO` (
  `Causa` VARCHAR(45) NOT NULL,
  `Fecha_Hora` DATETIME NOT NULL,
  `CUIL` INT NOT NULL,
  INDEX `fk_FALLECIDO_PACIENTE1_idx` (`CUIL` ASC) VISIBLE,
  CONSTRAINT `fk_FALLECIDO_PACIENTE1`
    FOREIGN KEY (`CUIL`)
    REFERENCES `covid`.`PACIENTE` (`CUIL`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `covid`.`HISTORIAL_CLINICO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `covid`.`HISTORIAL_CLINICO` (
  `IdDiagnostico` INT NOT NULL,
  `Informe` TEXT NOT NULL,
  `Enfermedad` VARCHAR(45) NULL,
  `Fecha_inicio` DATE NOT NULL,
  `Fecha_fin` VARCHAR(45) NULL,
  `Tratamiento` VARCHAR(45) NULL,
  `PACIENTE_CUIL` INT NOT NULL,
  `MEDICO_CUIL` INT NOT NULL,
  PRIMARY KEY (`IdDiagnostico`, `PACIENTE_CUIL`, `MEDICO_CUIL`),
  INDEX `fk_HISTORIAL_CLINICO_PACIENTE1_idx` (`PACIENTE_CUIL` ASC) VISIBLE,
  INDEX `fk_HISTORIAL_CLINICO_MEDICO1_idx` (`MEDICO_CUIL` ASC) VISIBLE,
  CONSTRAINT `fk_HISTORIAL_CLINICO_PACIENTE1`
    FOREIGN KEY (`PACIENTE_CUIL`)
    REFERENCES `covid`.`PACIENTE` (`CUIL`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_HISTORIAL_CLINICO_MEDICO1`
    FOREIGN KEY (`MEDICO_CUIL`)
    REFERENCES `covid`.`MEDICO` (`CUIL`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `covid`.`TESTEO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `covid`.`TESTEO` (
  `IdTesteo` INT NOT NULL,
  `Fecha` DATE NOT NULL,
  `Tipo` VARCHAR(45) NOT NULL,
  `Lugar` VARCHAR(45) NOT NULL,
  `Resultado` VARCHAR(45) NOT NULL,
  `PERSONA_CUIL` INT NULL,
  PRIMARY KEY (`IdTesteo`),
  INDEX `fk_TESTEO_PERSONA1_idx` (`PERSONA_CUIL` ASC) VISIBLE,
  CONSTRAINT `fk_TESTEO_PERSONA1`
    FOREIGN KEY (`PERSONA_CUIL`)
    REFERENCES `covid`.`PERSONA` (`CUIL`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
